# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoRecordAndTrimPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoRecordAndTrimPractice
	 pod 'RxSwift', '~> 4.5.0'
	 pod 'RxCocoa', '~> 4.5.0'
	 pod 'Then'
	 pod 'SnapKit'
	 pod 'Spitfire'

end
